export const realTimeActionTypes = {
  ADD: 'ADD',
  ADD_TEXTO: 'ADD_TEXTO',
  RESET_TOTAL: 'RESET_TOTAL',
  CRIAR_LISTA_SERVER: 'CRIAR_LISTA_SERVER',
  CRIAR_LISTA_CLASSIC: 'CRIAR_LISTA_CLASSIC',
  CRIAR_LISTA_CLIENT: 'CRIAR_LISTA_CLIENT',
};
